# Generated by Django 3.0.2 on 2020-01-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacker',
            name='computer_name',
            field=models.CharField(default='Anonymous Computer', max_length=200),
        ),
        migrations.AddField(
            model_name='victim',
            name='computer_name',
            field=models.CharField(default='Anonymous Computer', max_length=200),
        ),
    ]
