# Generated by Django 3.0.2 on 2020-02-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0003_auto_20200205_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacker',
            name='mac_address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victim',
            name='mac_address',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
