# Generated by Django 3.0.2 on 2020-02-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0005_auto_20200205_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
