# Generated by Django 3.0.3 on 2020-02-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0006_victim_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacker',
            name='victim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reverse_shell.Victim'),
        ),
    ]
