# Generated by Django 3.0.3 on 2020-03-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0007_attacker_victim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='logged_in',
            field=models.BooleanField(default=True),
        ),
    ]
