# Generated by Django 3.0.3 on 2020-03-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0008_auto_20200301_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attacker',
            name='victim',
        ),
    ]
