# Generated by Django 3.0.3 on 2020-03-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0009_remove_attacker_victim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victim',
            name='id',
        ),
        migrations.AlterField(
            model_name='victim',
            name='mac_address',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
