# Generated by Django 3.0.3 on 2020-03-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0010_auto_20200301_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attacker',
            name='id',
        ),
        migrations.AlterField(
            model_name='attacker',
            name='mac_address',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
