# Generated by Django 3.0.3 on 2020-03-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0013_auto_20200301_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
