# Generated by Django 3.0.3 on 2020-03-01 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0014_auto_20200301_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacker',
            name='victim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reverse_shell.Victim'),
        ),
    ]
