# Generated by Django 3.0.4 on 2020-03-20 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reverse_shell', '0017_auto_20200320_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacker',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attacker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='victim',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='victim', to=settings.AUTH_USER_MODEL),
        ),
    ]
