# Generated by Django 3.0.4 on 2020-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0018_auto_20200320_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacker',
            name='channel_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='channel_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
