# Generated by Django 3.0.4 on 2020-04-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0019_auto_20200401_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attacker',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='attacker',
            name='port',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='port',
        ),
    ]
