# Generated by Django 3.0.4 on 2020-04-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0020_auto_20200402_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attacker',
            name='computer_name',
        ),
        migrations.RemoveField(
            model_name='attacker',
            name='mac_address',
        ),
        migrations.AddField(
            model_name='attacker',
            name='name',
            field=models.CharField(blank=True, max_length=200, primary_key=True, serialize=False),
        ),
    ]
