# Generated by Django 3.0.4 on 2020-04-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_shell', '0021_auto_20200402_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='mac_address',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
